<?php

namespace App\Modules\Proposal\Requests;

use App\Modules\Proposal\Abstracts\BaseProposalRequest;
use App\Modules\Proposal\Enums\ProposalStatus;
use App\Modules\Proposal\Models\Proposal;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Gate;
use Illuminate\Validation\Rule;

class ProposalStoreRequest extends BaseProposalRequest
{
    public function rules(): array
    {
        return [
            ...parent::rules(),
            ...[
                /**
                 * Created by user (generated by server)
                 * @ignoreParam
                 */
                "created_by_user_id" => ["required", "integer:strict"],
                /**
                 * Initial status (generated by server)
                 * @ignoreParam
                 */
                "status" => ["required", Rule::enum(ProposalStatus::class)->only(ProposalStatus::DRAFT)],
            ],
        ];
    }

    public function authorize(): bool
    {
        Gate::authorize("create", Proposal::class);
        return true;
    }

    public function prepareForValidation(): void
    {
        parent::prepareForValidation();

        $this->merge([
            "status" => ProposalStatus::DRAFT->value,
            "created_by_user_id" => Auth::user()->id,
        ]);
    }
}
