<?php

namespace App\Modules\Auth\Abstracts;

use App\Abstracts\BaseFormRequest;
use App\Modules\Auth\Enums\UserRole;
use App\Modules\Auth\Enums\UserStatus;
use App\Rules\PhoneNumberRule;
use Illuminate\Validation\Rules\Enum as EnumRule;
use Illuminate\Validation\Rules\Password as PasswordRule;

abstract class BaseUserRequest extends BaseFormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {
        $id = \intval($this->route("id"));

        return [
            /**
             * First name
             * @example John
             */
            "first_name" => ["required", "string", "max:100"],
            /**
             * Last name
             * @example Rockstar
             */
            "last_name" => ["required", "string", "max:100"],
            /**
             * Email address
             * @example john.rockstar@gmail.com
             */
            "email" => ["required", "email", "unique:user,email,$id"],
            /**
             * Username
             * @example johnxrockstar01
             */
            "username" => ["required", "string", "max:40"],
            /**
             * Password (generated by server)
             * @ignoreParam
             */
            "password" => ["required", PasswordRule::default(), "max:30"],
            /**
             * Role
             */
            "role" => ["required", new EnumRule(UserRole::class)],
            /**
             * Status
             */
            "status" => ["required", new EnumRule(UserStatus::class)],
            /**
             * Phone number
             * @example +123456789
             */
            "phone_number" => ["required", new PhoneNumberRule(), "unique:user,phone_number,$id", "max:15"],
            /**
             * Position Id where user belongs to
             * @example 1
             */
            "position_id" => ["required"],
        ];
    }
}
