<?php

namespace App\Modules\Recruitment\Requests;

use App\Modules\Candidate\Enums\CandidateStatus;
use App\Modules\Candidate\Rules\CandidateExistsWithStatusRule;
use App\Modules\Proposal\Rules\RecruitmentExistsWithStatusRule;
use App\Modules\Recruitment\Abstracts\BaseRecruitmentApplicationRequest;
use App\Modules\Recruitment\Enums\RecruitmentApplicationPriority;
use App\Modules\Recruitment\Enums\RecruitmentApplicationStatus;
use App\Modules\Recruitment\Enums\RecruitmentStatus;
use App\Modules\Recruitment\Models\RecruitmentApplication;
use Illuminate\Support\Facades\Gate;
use Illuminate\Validation\Rule;

class RecruitmentApplicationStoreRequest extends BaseRecruitmentApplicationRequest
{
    public function rules(): array
    {
        return [
            /**
             * Id of Recuitment to apply
             * @example 1
             */
            "recruitment_id" => [
                "required",
                "integer:strict",
                new RecruitmentExistsWithStatusRule(RecruitmentStatus::PUBLISHED),
            ],
            /**
             * Id of Candidate to be applied
             * @example 1
             */
            "candidate_id" => [
                "required",
                "integer:strict",
                new CandidateExistsWithStatusRule(CandidateStatus::PENDING),
            ],
            /**
             * Initial status (generated by server)
             * @ignoreParam
             */
            "status" => [
                "required",
                Rule::enum(RecruitmentApplicationStatus::class)->only(RecruitmentApplicationStatus::PENDING),
            ],
            /**
             * Initial priority (generated by server)
             * @ignoreParam
             */
            "priority" => [
                "required",
                Rule::enum(RecruitmentApplicationPriority::class)->only(RecruitmentApplicationPriority::MEDIUM),
            ],
        ];
    }

    public function authorize(): bool
    {
        Gate::authorize("create", RecruitmentApplication::class);
        return true;
    }

    public function prepareForValidation(): void
    {
        parent::prepareForValidation();

        $this->merge([
            "status" => RecruitmentApplicationStatus::PENDING->value,
            "priority" => RecruitmentApplicationPriority::MEDIUM->value,
        ]);
    }
}
