<?php

namespace App\Modules\Recruitment\Requests;

use App\Modules\Candidate\Enums\CandidateStatus;
use App\Modules\Candidate\Rules\CandidateExistsWithStatusRule;
use App\Modules\Recruitment\Models\Recruitment;
use App\Modules\Recruitment\Rules\RecruitmentExistsWithStatusRule;
use App\Modules\Recruitment\Abstracts\BaseRecruitmentApplicationRequest;
use App\Modules\Recruitment\Enums\RecruitmentApplicationPriority;
use App\Modules\Recruitment\Enums\RecruitmentApplicationStatus;
use App\Modules\Recruitment\Enums\RecruitmentStatus;
use App\Modules\Recruitment\Models\RecruitmentApplication;
use Illuminate\Support\Facades\Gate;
use Illuminate\Validation\Rule;
use Illuminate\Validation\Validator;

class RecruitmentApplicationStoreRequest extends BaseRecruitmentApplicationRequest
{
    public ?Recruitment $recruitment = null;

    public function rules(): array
    {
        return [
            /**
             * Id of Recuitment to apply
             * @example 1
             */
            "recruitment_id" => [
                "required",
                "integer:strict",
                RecruitmentExistsWithStatusRule::create(RecruitmentStatus::PUBLISHED)->withRecruitment(
                    $this->recruitment,
                ),
            ],
            /**
             * Id of Candidate to be applied
             * @example 1
             */
            "candidate_id" => ["required", "integer:strict", new CandidateExistsWithStatusRule(CandidateStatus::READY)],
            /**
             * Initial status (generated by server)
             * @ignoreParam
             */
            "status" => [
                "required",
                Rule::enum(RecruitmentApplicationStatus::class)->only(RecruitmentApplicationStatus::PENDING),
            ],
            /**
             * Initial priority (generated by server)
             * @ignoreParam
             */
            "priority" => [
                "required",
                Rule::enum(RecruitmentApplicationPriority::class)->only(RecruitmentApplicationPriority::MEDIUM),
            ],
        ];
    }

    public function withValidator(Validator $validator): void
    {
        $validator->after(function (Validator $validator) {
            if (!$this->recruitment) {
                return;
            }

            $candidateId = $this->input("candidate_id");

            if ($this->recruitment->applications()->where("candidate_id", $candidateId)->exists()) {
                $validator->errors()->add("candidate_id", "Candidate has already applied for this recruitment.");
            }
        });
    }

    public function authorize(): bool
    {
        Gate::authorize("create", RecruitmentApplication::class);
        return true;
    }

    public function prepareForValidation(): void
    {
        parent::prepareForValidation();

        $this->recruitment = Recruitment::find($this->input("recruitment_id"));

        $this->merge([
            "status" => RecruitmentApplicationStatus::PENDING->value,
            "priority" => RecruitmentApplicationPriority::MEDIUM->value,
        ]);
    }
}
